config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trips

  devise_scope :user do
    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :country, presence: true
  validates :city, presence: true
  validate :validate_start_and_end_dates

  scope :twenty_four_hours_from_now, -> { where(start_date: 24.hours.from_now) }

  def validate_start_and_end_dates
    errors.add(:start_date, "Date cannot be in the past") if start_date.present? && start_date < Time.current
    errors.add(:end_date, "Date cannot be in the past") if end_date.present? && end_date < Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_in_path_for(resource)
    trips_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = current_user.trips.new(trip_params)
    get_weather_condition_service = GetWeatherConditionService.new(@trip)
    @trip.weather_condition = get_weather_condition_service.get_weather
    respond_to do |format|
      if @trip.save
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:name, :description, :user_id, :weather_condition, :start_date, :end_date, :city, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
  def display_weather_conditions(weather)
    weather.each do |w|
      "#{w['date']} - #{w['description']}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Findr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :start_date, as: :string, input_html: { type: :date }, start_year: Date.today.year %>
    <%= f.input :end_date,  as: :string, input_html: { type: :date }, start_year: Date.today.year %>
    <%= f.input :city %>
    <%= f.country_select :country %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        Name: <td><%= trip.name %></td>
        Description: <td><%= trip.description %></td>
        City: <td><%= trip.city %></td>
        Country: <td><%= trip.country %></td>
        Start Date: <td><%= trip.start_date %></td>
        End Date: <td><%= trip.end_date %></td>
        Weather Condition <% trip.weather_condition.each do |w| %>
        <td> <%= w['date'] %> - <%= w['description'] %><br> </td>
        <% end %>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>
<%= link_to 'Sign Out', destroy_user_session_path, class: "btn btn-default btn-sm"  %> 

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @trip.name %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        Name: <td><%= @trip.name %></td>
        Description: <td><%= @trip.description %></td>
        City: <td><%= @trip.city %></td>
        Country: <td><%= @trip.country %></td>
        Start Date: <td><%= @trip.start_date %></td>
        End Date: <td><%= @trip.end_date %></td>
        Weather Condition <% @trip.weather_condition.each do |w| %>
        <td> <%= w['date'] %> - <%= w['description'] %><br> </td>
        <% end %>
      </tr>
  </tbody>
</table>
<br>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>